In [10]:
import pandas as pd
import numpy as np
import os

In [13]:
root = '/Users/seanbajwa/Desktop/data_revival/clean_data/'

In [14]:
result = None
for year in os.listdir(root):
    if(year[0].isdigit()):
        df_list = []
        for sub_file in os.listdir(year):
            if(sub_file[-4:] == '.csv'):
                sub_dir = root + year + '/' + sub_file
                curr_df = pd.read_csv(sub_dir)
                df_list.append(curr_df)
        out_file = year + '.csv'
        out_dir = root + 'data/' + out_file
        print(out_dir)
        result = pd.concat(df_list)
        result.to_csv(out_dir)

/Users/seanbajwa/Desktop/data_revival/clean_data/data/2013.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2014.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2012A.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2015A.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2010B.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2008B.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2001.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2006.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2007.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2000.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2009.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2011.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2016.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2012B.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2010A.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2015B.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2008A.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2005.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2002.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2003.csv
/Users/seanbajwa/Desktop/data_revival/clean_data/data/2004.csv

In [15]:
data_root = root + 'data/'

In [16]:
combine_list = []
for file in os.listdir(data_root):
    year = file[:-4]
    curr_df = pd.read_csv(data_root + file)
    curr_df['YEAR'] = year
    combine_list.append(curr_df)
    #print(curr_df.columns)
all_df = pd.concat(combine_list)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (16,47,50) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (47,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [17]:
all_df.head()

,Unnamed: 0,HCPCS CODE,MODIFIER,SHORT DESCRIPTION,PROC STAT,MAC LOCALITY,NON-FACILITY PRICE,FACILITY PRICE,NON-FACILITY LIMITING CHARGE,FACILITY LIMITING CHARGE,...,CONV FACT.1,NOT USED FOR MEDICARE.1,DIAG IMAGING FAMILY IND,OPPS NON-FACILITY PAYMENT AMOUNT<sup>1</sup>,OPPS FACILITY PAYMENT AMOUNT<sup>1</sup>,NON-FAC PE USED FOR OPPS PMT AMT,FACILITY PE USED FOR OPPS PMT AMT,MALPRACTICE USED FOR OPPS PMT AMT,Unnamed: 56,YEAR
0,0,92520,NaN,Laryngeal function studies,A,51000,$53.43,$36.51,$58.37,$39.89,...,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,NaN,2009
1,1,92520,NaN,Laryngeal function studies,A,51199,$54.70,$37.18,$59.76,$40.62,...,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,NaN,2009
2,2,92520,NaN,Laryngeal function studies,A,52013,$53.16,$36.38,$58.08,$39.75,...,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,NaN,2009
3,3,92520,NaN,Laryngeal function studies,A,52801,$59.71,$39.00,$65.24,$42.61,...,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,NaN,2009
4,4,92520,NaN,Laryngeal function studies,A,59003,$60.33,$40.13,$65.91,$43.84,...,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,NaN,2009

In [22]:
all_df = all_df.drop(columns=['Unnamed: 56'])

In [23]:
all_df.head()

,HCPCS CODE,MODIFIER,SHORT DESCRIPTION,PROC STAT,MAC LOCALITY,NON-FACILITY PRICE,FACILITY PRICE,NON-FACILITY LIMITING CHARGE,FACILITY LIMITING CHARGE,CONV FACT,...,ENDOBASE,CONV FACT.1,NOT USED FOR MEDICARE.1,DIAG IMAGING FAMILY IND,OPPS NON-FACILITY PAYMENT AMOUNT<sup>1</sup>,OPPS FACILITY PAYMENT AMOUNT<sup>1</sup>,NON-FAC PE USED FOR OPPS PMT AMT,FACILITY PE USED FOR OPPS PMT AMT,MALPRACTICE USED FOR OPPS PMT AMT,YEAR
0,92520,NaN,Laryngeal function studies,A,51000,$53.43,$36.51,$58.37,$39.89,36.0666,...,NaN,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,2009
1,92520,NaN,Laryngeal function studies,A,51199,$54.70,$37.18,$59.76,$40.62,36.0666,...,NaN,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,2009
2,92520,NaN,Laryngeal function studies,A,52013,$53.16,$36.38,$58.08,$39.75,36.0666,...,NaN,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,2009
3,92520,NaN,Laryngeal function studies,A,52801,$59.71,$39.00,$65.24,$42.61,36.0666,...,NaN,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,2009
4,92520,NaN,Laryngeal function studies,A,59003,$60.33,$40.13,$65.91,$43.84,36.0666,...,NaN,36.0666,NaN,99.0,NaN,NaN,0.0,0.0,0.0,2009

In [24]:
all_df.to_csv(data_root + 'ALL_YEARS.csv')

In [25]:
all_df['HCPCS CODE']

0        92520
1        92520
2        92520
3        92520
4        92520
5        92520
6        92520
7        92520
8        92520
9        92520
10       92520
11       92520
12       92520
13       92520
14       92520
15       92520
16       92520
17       92520
18       92520
19       92520
20       92520
21       92520
22       92520
23       92520
24       92520
25       92520
26       92520
27       92520
28       92520
29       92520
         ...
58028    96150
58029    96150
58030    96150
58031    96150
58032    96150
58033    96150
58034    96150
58035    96150
58036    96150
58037    96150
58038    96150
58039    96150
58040    96150
58041    96150
58042    96150
58043    96150
58044    96150
58045    96150
58046    96150
58047    96150
58048    96150
58049    96150
58050    96150
58051    96150
58052    96150
58053    96150
58054    96150
58055    96150
58056    96150
58057    96150
Name: HCPCS CODE, Length: 1129873, dtype: int64

In [26]:
def getCodes(file):
    codes = set()
    with open(file) as f:
        for line in f:
            if len(line) > 0:
                line = line.strip()
                codes.add(line)
    return codes

In [31]:
code_file = '/Users/seanbajwa/Desktop/data_revival/hcpc_codes.txt'

In [34]:
codes = list(getCodes(code_file))

In [36]:
len(codes)

555

In [80]:
import warnings
warnings.filterwarnings('ignore')

In [81]:
new_root = root+ 'data/'

In [82]:
years = [year for year in os.listdir(new_root) if(year[0].isdigit())]

In [83]:
year_len = len(years)

In [84]:
code_dict = {}
for code in codes:
    year_list = [None]*(year_len)
    for i in range(len(years)):
        year = years[i]
        curr_df = pd.read_csv(new_root + year)
        code_list = list(set(curr_df['HCPCS CODE'].tolist()))
        if(int(code) in code_list):
            year_list[i] = True
        else:
            year_list[i] = False
    code_dict[code] = year_list

In [60]:
str_years = [str([year[:-4]]) for year in years]

In [62]:
data = []
for key in code_dict:
    key_list = code_dict[key]
    row = [key] + key_list
    data.append(row)

TypeError: object of type 'NoneType' has no len()

In [ ]:
str_years = ['HCPCS CODE'] + str_years
bool_df = pd.Dataframe(data, columns=str_years)
bool_df.head()